# Generated by Django 4.2.11 on 2024-07-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("betlord", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
