# Generated by Django 4.2.11 on 2024-07-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("betlord", "0002_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bet",
            name="team1",
        ),
        migrations.RemoveField(
            model_name="bet",
            name="team2",
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team1",
                        to="betlord.team",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team2",
                        to="betlord.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bet",
            name="match",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bets",
                to="betlord.match",
            ),
        ),
    ]
